//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Subjectt { get; set; }
        public string Massege { get; set; }
        public int Cid { get; set; }
    }
}
